name: Close TW Pull Request

on:
  pull_request_target:
    types: [opened]
    paths: previous-seasons/2023-participants/interested-technical-writers.md

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        # Optional. Post a issue comment just before closing a pull request.
        comment: "The 2023 Season of Docs program is complete, so we're closing this PR. Please feel free to subscribe to our [announcements list](https://groups.google.com/g/season-of-docs-announce) for information about upcoming Google Season of Docs programs."
